### ISSUE TITLE
装備ウィンドウの挙動について

### ISSUE THREAD

**Issue by batow62** [kcjervis/jervis#29]
スロット機数をドラッグし続けると装備のウィンドウがマウスを追従して動くのは仕様でしょうか？

https://gyazo.com/a56361003024f99bbf1f70d20ff6fc9b

**Comment by MadonoHaru** [comment]
装備ウィンドウはドラッグ出来るようになっています
スロット機数の変更に邪魔でしたら対策を考えます

**Comment by batow62** [comment]
装備ウィンドウがドラッグ移動できるのは気が付きませんでした。
もともとドラッグでウィンドウ移動できるのであれば問題ないと思います。
回答ありがとうございました。
