### ISSUE TITLE
改修による火力・雷装値の上昇がない

### ISSUE THREAD

**Issue by batow62** [kcjervis/jervis#30]
以下の画像のように改修による火力・雷装値の上昇が正しく反映されていないようです。
https://gyazo.com/ea2387797ff4f48108ee03c8490d353b

> 「白露型駆逐艦、朝潮型駆逐艦、陽炎型駆逐艦、夕雲型駆逐艦」の改二に★max状態で装備すると火力+1される。
>「白露型駆逐艦、朝潮型駆逐艦、陽炎型駆逐艦、夕雲型駆逐艦」の改二に装備すると、雷装+2, 回避+1される。

参考リンク:[攻略wiki](https://wikiwiki.jp/kancolle/61cm%E5%9B%9B%E9%80%A3%E8%A3%85%28%E9%85%B8%E7%B4%A0%29%E9%AD%9A%E9%9B%B7%E5%BE%8C%E6%9C%9F%E5%9E%8B)

**Comment by MadonoHaru** [comment]
修正しました
