### ISSUE TITLE
一部装備構成で40種・41種対空CIが発動されない

### ISSUE THREAD

**Issue by DQue** [kcjervis/jervis#43]
Atlanta改に5inch連装両用砲(集中配備)を2つ装備した場合に41種対空カットイン、
加えてGFCS Mk.37を装備した場合に40種対空カットインが発動するはずですが、
作戦室上では5種のみが表示されます。
バグの発生ページ：https://jervis.page.link/uFZz
資料：https://wikiwiki.jp/kancolle/対空砲火#antiairfire

**Comment by MadonoHaru** [comment]
ありがとうございます！
